ansible_user: "root"
ansible_password: "tmp"

packages_to_install:
  - "python3-pip"
  - "zsh"
  - "git"
  - "lsof"
  - "netcat"

# Role variables
target_username: "root"

# sshd_config variables
ssh_port: 22
PermitRootLogin: "yes"
PasswordAuthentication: "yes"
ClientAliveInterval: 30
ClientAliveCountMax: 240
# whether to generate or not new keys
new_ssh_host_keys: false
new_ssh_user_keys: false

# Shell and optional zsh customization
new_default_shell: "/bin/zsh"

OhMyZsh_install: true
# installing p10k with this role requires OhMyZsh_install to be true
OhMyZsh_install_powerlevel10k: true
OhMyZsh_path: "/opt/ohmyzsh"
# keep_zshrc needs to be either "yes" or "no"
OhMyZsh_keep_zshrc: "no"
# if install_powerlevel10k is true, it will copy a p10k config
OhMyZsh_copy_config: true

# Swap file settings
swap_file_path: "/swap"
swap_file_size_mb: 2048
