---
# tasks file for SWAP_setup
- name: Get swap size
  shell: du -sh --apparent-size "{{ swap_file_path }}" | cut -d 'G' -f 1
  register: system_swap_size
  ignore_errors: true

- debug:
    msg: "The host has {{ system_swap_size.stdout }}GiB dedicated to swap"
  when: system_swap_size is defined

- block:
    - name: Turn off all swap and remove {{ swap_file_path }}
      shell: swapoff -a; rm -f {{ swap_file_path }}
      tags:
        - swap.file.disable

    - name: Create swap file
      command: |
        dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size_mb }}k
      tags:
        - swap.file.create

    - name: Change swap file permissions
      file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600
      tags:
        - swap.file.permissions

    - name: Make swap file
      command: "mkswap {{ swap_file_path }}"
      tags:
        - swap.file.mkswap

    - name: Mount swap
      command: "swapon {{ swap_file_path }}"
      tags:
        - swap.file.swapon

  when: >
    (( system_swap_size.stdout | float ) != ( swap_file_size_mb | float )/1024) or
    (system_swap_size is not defined)
  become: true
